# Generated by Django 6.1.1 on 2026-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
